### PR TITLE
Start exporter after network is up

### PR DESCRIPTION
**Pull request by Rohlik**

### CODE REVIEW

**Comment by meowtochondria** [comment]
From [official documentation](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/#conceptsinsystemd) - adding dependency on `network-online.target` may delay instance boot up time in slow network environments. In this case, because we are starting up with a pseudo address [`0.0.0.0`](https://github.com/meowtochondria/node_exporter-rpm/blob/master/SOURCES/environment.conf#L3) as recommended in docs, I think depending just on `network.target` is the right thing to do. I am also uncertain of what would happen to the unit if there is a temporary network issue - would the exporter stop collecting metrics for that time even though nothing else was wrong with machine? If the unit will stop, then there will be preventable gaps in metrics.

I would like to hear your thoughts.

**Comment by Rohlik** [comment]
> Adding dependency on network-online.target may delay instance boot up time in slow network environments.

You are right about potentional slow boot up in some cases.



> Would the exporter stop collecting metrics for that time even though nothing else was wrong with machine?

This is the interesting part, because exporter collect metrics only if you connect to exporter's `/metrics` URI. And you cannot connect to exporter when host network is not up, right? This is why I created this pull request in the first place.

**Comment by meowtochondria** [comment]
I did some study on my own since over last few days, and yes the metrics are only collected by `node_exporter` when we hit `/metrics`.

Your idea certainly holds when we are scraping over network. I believe that over-network scraping is not the only use case. Considering how fairly lightweight is Prometheus stack, I can think of use cases, such as demos, where depending on `network-online.target` might be an overkill.

**Comment by Rohlik** [comment]
You are right, I close this pull request. Thanks for the great discussion ;-)

**Pull request closed without merging**
